# Generated by Django 6.0.3 on 2026-03-19 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_mymodel_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
